__author__ = 'Neil Butcher'

from widget_appointment_list import AppointmentsListWidget
from widget_appointment import SingleAppointmentWidget
from widget_appointment_tree import AppointmentsTreeListWidget